### ISSUE TITLE
Telebit.io domain no longer returning correct IP address

### ISSUE THREAD

**Issue by smalls3000i** [therootcompany/telebit#3]
woke up this morning an could not go to my forwarded domain, when i did a ns lookup it did not show the company as the parent domain whats going on, have i been hacked or have yall been hacked idk, it was working great and i did nothing website is shy-lion-88.telebit.io, please help if you can, if no say no and ill move on, but i liked that url

hope this finds someone soon peace <3

**Comment by coolaj86** [comment]
Nothing so nefarious.

1. I updated my credit card on file months ago because it was expiring
2. Apparently this triggered "auto-renew" to turn off for my domains
3. I've been sick in bed, sleeping the whole day the last few days
4. The domain expired Friday
5. Today I manually clicked the renew button

All should be well soon.

**Comment by smalls3000i** [comment]
awwww thank you very very much im broke, but if i had money id give you i
really wish you get well soon, and its nothing too serious, say a pray it
works, love you, and keep smiling you look soo much better when you smile

**Comment by smalls3000i** [comment]
it works perfectly now, thank you very much, you are an amazing person and soo too is your work, thank you once again, and GET WELL SOOOOOON!!!!!!!  <3 <3 <3

**Comment by smalls3000i** [comment]
also i cant thank you enough, butt now my question is seeing that auto
renew is off, does this mean that now you would have to click it everytime,
i don't want to interrupt your healing process, i'm really so i messaged
soo many times to now ask this

**Comment by coolaj86** [comment]
I turned the auto-renew back on.

**Comment by smalls3000i** [comment]
Hey season greetings, can I ask to update my ns to kevin.ns.cloudflare.com I'm
trying to give my  telebit subdomain cloudflare cdn, my url is
https://shy-lion-88.telebit.io i just wanna see if I can add the cloudflare
proxy

**Comment by Troptrap** [comment]
The same happened this week, I think.
